language: java

dist: trusty
sudo: false
jdk: openjdk8

jobs:
  include:
    - stage: build
      script: gradle build -x test --no-daemon
    - stage: test
      script: gradle build --no-daemon

cache:
  directories:
    - ~/.gradle

