language: java

dist: trusty
sudo: false
jdk: openjdk8

jobs:
  include:
    - stage: build
      install: true # Skip gradle assemble
      script: gradle build -x test -x signArchives

    - stage: test
      install: true # Same as in build
      script: gradle check -x signArchives

    - stage: snapshot publication
      if: type != pull_request AND tag IS blank
      env:
        - MAVEN_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots/"
      before_install:
        - openssl aes-256-cbc -K $encrypted_23c9d51bee08_key -iv $encrypted_23c9d51bee08_iv -in ci/ci-secrets.tar.enc -out ci/ci-secrets.tar -d
        - tar xvf ci/ci-secrets.tar -C ./ci
        - mv ci/ci-signing.gradle.properties ./gradle.properties
      install:
        - true # Same as above
      script:
        - gradle uploadArchives

    - stage: publish
      if: tag IS present
      env:
        - BUILD_VERSION="$TRAVIS_TAG"
        - MAVEN_REPO_URL="https://oss.sonatype.org/service/local/staging/deploy/maven2/"
      before_install:
        - openssl aes-256-cbc -K $encrypted_23c9d51bee08_key -iv $encrypted_23c9d51bee08_iv -in ci/ci-secrets.tar.enc -out ci/ci-secrets.tar -d
        - tar xvf ci/ci-secrets.tar -C ./ci
        - mv ci/ci-signing.gradle.properties ./gradle.properties
      install:
        - true # Same as above
      script:
        - gradle uploadArchives

cache:
  directories:
    - ~/.gradle

