language: java

dist: trusty
sudo: false
jdk: openjdk8

jobs:
  include:
    - stage: build
      install: true # Skip gradle assemble
      script: gradle build -x test -x signArchives

    - stage: test
      install: true # Same as in build
      script: gradle check -x signArchives

    - stage: snapshot publication
      if: type != pull_request AND tag IS blank
      env:
        - MAVEN_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots/"
        - secure: "FPopyKS4Gdaf/QCopgQSD/JQ14o3W77PekUa2US6A1TjEvi7eCY5gJ4cPtKJjwzhHt342QvsT5yV3N7KQiEb9pfmCkYKSZmBcGZnu1cRhh9cFvHLWjFKdtqGyKrYdWOWc6WGpQueE1myW+TAJzoDg8CSXU85EcCD8RdSGmC579NQ6dDlurD8j39iWZkAUOAO23CUHwkzE9snrVz5ZP7yIT3Wyqcx1raI48Z3cFopWrvBNsCrwldVUe8qPMm9NSLIQ5c7lEjNMZYhw3ebMEvK5t9F4b4f03izKIFDVzR3szRpChKf0Jq7C6KU3ckvQkrX0Z5TkXIu0imoYQ9iZyOb6TWVEPe86X10SHjsb1iAJ1h3H2PHFR0NyRVozYTCnHLCUnZsIoZRwDq/ga6ulGi8Ie997PUq4rFy9GuktRnSYo4Wv953LHeXz4WMqeznsCEX7q7nEwhKvhU+3ro3kPlViqbX3bwo5oWRwBx47RcuCmp78aRSBY5o+GLBHnMM5HBxEydskNStfrKlceoMSlyyIVAB06eeZbQM4bN6WianmfGs13PGqbMnrNsQ39RVKreW6yW67ubablljQDe2VHGhlLjdUqrHKv8nCSSFJsNPptI2ERg5Pjvwl+QD6zxQGwq1Z3VC4pbbh9zODeRfLv0DZri+XvlZ6r5jmCcbwUEEcjU="
        - secure: "S/MfAG6YvMLEp5gF0QHtdlH2h4+oz52LAe+xeOWxmuHPqvQ1aOAJEqXSkiVBx0F6yMPoMNCFOMcGe/f+VmCJI6BsKXtT76M7gbypkfu68qeuRxRUWKFIWP2pJFeubX1YNy3l3xt/Phv2BxtTNKsLP3b61z1xeUwqoA25W2yzYb9LcuiC5mKaZ4HU4QRslXNwl+gwLVesQNSFgzKTslyGxCwg7X56B7IIgSeL64HN+7YbX6LN5bCHv3a2mHL+4oF+VnyCbl2axA2is97N9oCSXE7uCdXbMAFdOvf2UyRY9l+fONtHoQSl1aYkcVvz0YvYJ7xaXzpEjvUvR49bm+AfmfnGhJp2GQIFR1Eoc2mol4A8i0gadjLmpSzplTBlX6n9HOnDyzLH0RGUbJAs3b9gDSyowbCi3HY5rsnvzhJLtn6Wanv3BNUNOhD3dvt77NK/6wLDGp+v/qbBvma3PpHsUv6ocWNwFnR22I564MA1W+5OFg8TQbwlEbegAV0gLUEsbyKYamk8fLh23OjamSLhbzQU0QEIz0NrSO/kKJDwyelcd+DdJu5o3DMN6KAEKwHgbnEIudc9T4JHO9kSdnK5rIYdgaluf6HeJ+EbnkwH7kFTmcloAKyAwIcp+E391NbXwmY7GZuqcBHkLwPre5kPl9nNdjGDzkmCLp7VOWwcDLA="
      before_install:
        - openssl aes-256-cbc -K $encrypted_23c9d51bee08_key -iv $encrypted_23c9d51bee08_iv -in ci/ci-secrets.tar.enc -out ci/ci-secrets.tar -d
        - tar xvf ci/ci-secrets.tar -C ./ci
        - mv ci/ci-signing.gradle.properties ./gradle.properties
      install:
        - true # Same as above
      script:
        - gradle uploadArchives

    - stage: publish
      if: tag IS present
      env:
        - MAVEN_REPO_URL="https://oss.sonatype.org/service/local/staging/deploy/maven2/"
        - secure: "FPopyKS4Gdaf/QCopgQSD/JQ14o3W77PekUa2US6A1TjEvi7eCY5gJ4cPtKJjwzhHt342QvsT5yV3N7KQiEb9pfmCkYKSZmBcGZnu1cRhh9cFvHLWjFKdtqGyKrYdWOWc6WGpQueE1myW+TAJzoDg8CSXU85EcCD8RdSGmC579NQ6dDlurD8j39iWZkAUOAO23CUHwkzE9snrVz5ZP7yIT3Wyqcx1raI48Z3cFopWrvBNsCrwldVUe8qPMm9NSLIQ5c7lEjNMZYhw3ebMEvK5t9F4b4f03izKIFDVzR3szRpChKf0Jq7C6KU3ckvQkrX0Z5TkXIu0imoYQ9iZyOb6TWVEPe86X10SHjsb1iAJ1h3H2PHFR0NyRVozYTCnHLCUnZsIoZRwDq/ga6ulGi8Ie997PUq4rFy9GuktRnSYo4Wv953LHeXz4WMqeznsCEX7q7nEwhKvhU+3ro3kPlViqbX3bwo5oWRwBx47RcuCmp78aRSBY5o+GLBHnMM5HBxEydskNStfrKlceoMSlyyIVAB06eeZbQM4bN6WianmfGs13PGqbMnrNsQ39RVKreW6yW67ubablljQDe2VHGhlLjdUqrHKv8nCSSFJsNPptI2ERg5Pjvwl+QD6zxQGwq1Z3VC4pbbh9zODeRfLv0DZri+XvlZ6r5jmCcbwUEEcjU="
        - secure: "S/MfAG6YvMLEp5gF0QHtdlH2h4+oz52LAe+xeOWxmuHPqvQ1aOAJEqXSkiVBx0F6yMPoMNCFOMcGe/f+VmCJI6BsKXtT76M7gbypkfu68qeuRxRUWKFIWP2pJFeubX1YNy3l3xt/Phv2BxtTNKsLP3b61z1xeUwqoA25W2yzYb9LcuiC5mKaZ4HU4QRslXNwl+gwLVesQNSFgzKTslyGxCwg7X56B7IIgSeL64HN+7YbX6LN5bCHv3a2mHL+4oF+VnyCbl2axA2is97N9oCSXE7uCdXbMAFdOvf2UyRY9l+fONtHoQSl1aYkcVvz0YvYJ7xaXzpEjvUvR49bm+AfmfnGhJp2GQIFR1Eoc2mol4A8i0gadjLmpSzplTBlX6n9HOnDyzLH0RGUbJAs3b9gDSyowbCi3HY5rsnvzhJLtn6Wanv3BNUNOhD3dvt77NK/6wLDGp+v/qbBvma3PpHsUv6ocWNwFnR22I564MA1W+5OFg8TQbwlEbegAV0gLUEsbyKYamk8fLh23OjamSLhbzQU0QEIz0NrSO/kKJDwyelcd+DdJu5o3DMN6KAEKwHgbnEIudc9T4JHO9kSdnK5rIYdgaluf6HeJ+EbnkwH7kFTmcloAKyAwIcp+E391NbXwmY7GZuqcBHkLwPre5kPl9nNdjGDzkmCLp7VOWwcDLA="
      before_install:
        - openssl aes-256-cbc -K $encrypted_23c9d51bee08_key -iv $encrypted_23c9d51bee08_iv -in ci/ci-secrets.tar.enc -out ci/ci-secrets.tar -d
        - tar xvf ci/ci-secrets.tar -C ./ci
        - mv ci/ci-signing.gradle.properties ./gradle.properties
      install:
        - true # Same as above
      script:
        - gradle uploadArchives

cache:
  directories:
    - ~/.gradle

